.TH SMP_PHY_CONTROL "8" "June 2006" "smp_utils-0.90" SMP_UTILS
.SH NAME
smp_phy_control \- invoke PHY CONTROL SMP function
.SH SYNOPSIS
.B smp_phy_control
[\fI--help\fR] [\fI--hex\fR] [\fI--interface=<params>\fR] [\fI--min=<n>\fR]
[\fI--max=<n>\fR] [\fI--op=<op>\fR] [\fI--phy=<n>\fR] [\fI--pptv=<n>\fR]
[\fI--raw\fR] [\fI--sa=<sas_addr>\fR] [\fI--verbose\fR] [\fI--version\fR]
\fI<smp_device>[,<n>]\fR
.SH DESCRIPTION
.\" Add any additional description here
.PP
Sends a SAS Management Protocol (SMP) PHY CONTROL request function
to a SMP target. The SMP target is identified by the <smp_device>
and the <sas_addr>. Depending on the interface, the <sas_addr>
may be deduced from the <smp_device>. With one interface there is
one <smp_device> per machine so the '<smp_device>,<n>' syntax is
needed to differentiate between HBAs if there are multiple present.
.PP
The PHY CONTROL function is used to change the state of a phy
within a SMP target. SMP targets are typically SAS expanders
which have multiple phys. Certain operation
values (e.g. 'lr' (link reset) and 'hr' (hard reset)) change the
state of the attached phy. Sending such operation values to the
phy in the SMP target that is attached to the originator (i.e. the
SMP initiator) may lead to a bad response.
.PP
Invoking this utility with no arguments (other than <smp_device>
which might be in an environment variable and '--sa=<sas_addr>'
which might be in an environment variable or not needed) is
harmless. In other words a phy's state is only changed when
either '--max=', '--min=', '--op=' or '--pptv=' is given
with a non default value.
.TP
--help | -h
output the usage message then exit.
.TP
--hex | -H
output the response in hexadecimal.
.TP
--interface=<params> | -I <params>
interface specific parameters. In this case "interface" refers to the
path through the operating system to the SMP initiator. See the smp_utils
man page for more information.
.TP
--min=<n> | -m <n>
permits the programmed minimum physical link rate to be changed on the
given phy. Permitted values are: 0 -> no change, 8 -> 1.5 Gbps, 9 -> 3 Gbps,
10 -> 6 Gbps. Default value is 0.
.TP
--max=<n> | -M <n>
permits the programmed maximum physical link rate to be changed on the
gven phy. Permitted values are: 0 -> no change, 8 -> 1.5 Gbps, 9 -> 3 Gbps,
10 -> 6 Gbps. Default value is 0.
.TP
--op=<op> | -o <op>
specifies the operation to be performed on the given phy. The <op> argument
can be either numeric or a string. If a number is given, it is put into
the 'phy operation' field of the request. Allowable strings are abbreviations
of which only the first two characters need to match. The supported strings
are: 'nop' (no operation), 'lr' (link reset), 'hr' (hard reset), 'dis' (disable
phy), 'cel' (clear error log), 'ca' (clear affiliation), 'tspss' (transmit
SATA port selection signal) and 'citnl' (clear STP I_T nexus loss (bit)).
The default value is 0 (no operation).
.TP
--phy=<n> | -p <n>
phy identifier. This is a value between 0 and 127. Default is 0.
.TP
--pptv=<n> | -P <n>
partial pathway timeout value. The units are microseconds and the permitted
values are between 0 and 15 inclusive. 7 microseconds is recommended by
sas2r03apdf.
.TP
--raw | -r
send the response to stdout in binary. All error messages are sent to stderr.
.TP
--sa=<sas_addr> | -s <sas_addr>
specifies the SAS address of the SMP target device. Typically this is an
expander. This option may not be needed if the <smp_device> has the target's
SAS address within it. The <sas_addr> is in decimal but most SAS addresses
are shown in hexadecimal. The give a number in hexadecimal either prefix
it with '0x' or put a trailing 'h' on it.
.TP
--verbose | -v
increase the verbosity of the output. Can be used multiple times
.TP
--version | -V
print the version string and then exit.
.SH AUTHORS
Written by Douglas Gilbert.
.SH "REPORTING BUGS"
Report bugs to <dgilbert at interlog dot com>.
.SH COPYRIGHT
Copyright \(co 2006 Douglas Gilbert
.br
This software is distributed under a FreeBSD license. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.B smp_utils, smp_discover(smp_utils)
