.TH SMP_CONF_ROUTE_INFO "8" "June 2006" "smp_utils-0.90" SMP_UTILS
.SH NAME
smp_conf_route_info \- invoke CONFIGURE ROUTE INFORMATION SMP function
.SH SYNOPSIS
.B smp_conf_route_info
[\fI--disable\fR] [\fI--help\fR] [\fI--hex\fR] [\fI--index=<n>\fR]
[\fI--interface=<params>\fR] [\fI--phy=<n>\fR] [\fI--raw\fR]
[\fI--routed=<sas_addr>\fR] [\fI--sa=<sas_addr>\fR] [\fI--verbose\fR]
[\fI--version\fR] \fI<smp_device>[,<n>]\fR
.SH DESCRIPTION
.\" Add any additional description here
.PP
Sends a SAS Management Protocol (SMP) CONFIGURE ROUTE INFORMATION
request function to a SMP target. The SMP target is identified by
the <smp_device> and the '--sa=<sas_addr>'. Depending on the interface,
the <sas_addr> may be deduced from the <smp_device>. With one interface there is
one <smp_device> per machine so the '<smp_device>,<n>' syntax is
needed to differentiate between HBAs if there are multiple present.
.PP
Each phy in a SAS expander that has an associated routing attribute
of "table" has a router table. The number of rows (or entries) in
each router table is given by the "expander route indexes" field
in the response of the REPORT GENERAL function.
.TP
--disable | -d
set the "disable expander route entry" flag in a row of the router table
associated with '--phy=<n>' of the given SMP target (e.g. an expander).
Within the router table the row that is disabled is identified by
the expander route index given by '--index=<n>'.
.TP
--help | -h
output the usage message then exit.
.TP
--hex | -H
output the response in hexadecimal.
.TP
--index=<n> | -i <n>
expander route index. This is a value between 0 and 65535. Default is 0.
More precisely the maximum index value is (expander_route_indexes - 1).
.TP
--interface=<params> | -I <params>
interface specific parameters. In this case "interface" refers to the
path through the operating system to the SMP initiator. See the smp_utils
man page for more information.
.TP
--phy=<n> | -p <n>
phy identifier. This is a value between 0 and 127. Default is 0.
.TP
--raw | -r
send the response to stdout in binary. All error messages are sent to stderr.
.TP
--routed=<sas_addr> | -R <sas_addr>
specifies the SAS address to be placed in a row (given by '--index=<n>') of
the router table associated with '--phy=<n>'. Default value is 0.
The <sas_addr> is in decimal but most SAS addresses are given in hexadecimal.
The give a number in hexadecimal either prefix it with '0x' or put a
trailing 'h' on it.
.TP
--sa=<sas_addr> | -s <sas_addr>
specifies the SAS address of the SMP target device. Typically this is an
expander. This option may not be needed if the <smp_device> has the target's
SAS address within it. The <sas_addr> is in decimal but most SAS addresses
are shown in hexadecimal. The give a number in hexadecimal either prefix
it with '0x' or put a trailing 'h' on it.
.TP
--verbose | -v
increase the verbosity of the output. Can be used multiple times
.TP
--version | -V
print the version string and then exit.
.SH AUTHORS
Written by Douglas Gilbert.
.SH "REPORTING BUGS"
Report bugs to <dgilbert at interlog dot com>.
.SH COPYRIGHT
Copyright \(co 2006 Douglas Gilbert
.br
This software is distributed under a FreeBSD license. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.B smp_utils, smp_rep_general(smp_utils), smp_rep_route_info(smp_utils)
